version: "3.9"
services:
  qrcode:
    container_name: QR-Code-Generator
    image: bizzycolah/qrcode-generator:latest
    healthcheck:
     test: curl -f http://localhost:80/ || exit 1
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    ports:
      - 8895:80