version: "3.9"
services:
  lingva:
    image: thedaviddelta/lingva-translate:latest
    container_name: Lingva-Translate
    hostname: lingva
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    ports:
      - 6455:3000
    environment:
      #site_domain: lingva.yourname.synology.me
      force_default_theme: dark
      default_source_lang: auto
      default_target_lang: en
    restart: on-failure:5
